[project]
name = "comfyui_if_memoavatar"
description = "ComfyUI MemoAvatar"
version = "0.0.3"
license = { file = "MIT License" }
dependencies = [
    "albumentations==1.4.21",
    "modelscope==1.20.1",
    "numba==0.60.0",
    "librosa==0.10.2",
    "diffusers>=0.31.0",
    "transformers>=4.46.3",
    "numpy>=1.26.4",
    "PyYAML>=6.0.1",
    "moviepy==1.0.3",
    "pillow>=10.4.0",
    "funasr==1.0.27",
    "insightface==0.7.3",
    "accelerate==1.1.1",
    "black==23.12.1",
    "ffmpeg-python==0.2.0",
    "huggingface-hub==0.26.2",
    "imageio==2.36.0",
    "imageio-ffmpeg==0.5.1",
    "hydra-core==1.3.2",
    "jax==0.4.35",
    "mediapipe==0.10.18",
    "omegaconf==2.3.0",
    "onnxruntime-gpu>=1.20.1",
    "opencv-python-headless==4.10.0.84",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "tqdm>=4.67.1",
]

[project.urls]
Repository = "https://github.com/if-ai/ComfyUI-IF_MemoAvatar"

[tool.comfy]
PublisherId = "impactframes"
DisplayName = "IF_MemoAvatar"
Icon = "https://impactframes.ai/System/Icons/48x48/if.png"
